language: node_js
node_js:
  - stable
  - lts/boron
  - lts/argon
after_success:
  - npm install --global coveralls
  - npm run coverage
  - ./node_modules/.bin/nyc report --reporter=text-lcov | coveralls
